project:
  type: website

website:
  title: "<img src='/images/Logo.png' alt='IA_Logo' style='width: 4em; height: 4em; border-radius: 30%;'> <b>Evolution of Global Poverty</b>"
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO-526-S24/project-final-InsightArchitect
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd
      - text: Dashboard
        href: Dashboard.qmd
        

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true

execute:
  freeze: auto
